<!-- general form elements disabled -->
<div class="card card-secondary">
    <div class="card-body">
        <?php
        $form->setAttribute('action', $this->url($table->getRoute()));
        $form->setAttribute('method', 'GET');
        echo $this->form()->openTag($form);
        ?>
            <div class="row">
                <?php
                /** @var \Laminas\Form\Form $form */
                foreach ($form->getElements() as $element):
                ?>
                <div class="col-sm-3">
                    <div class="form-group">
                        <?php
                        echo $this->formElement()->render($element);
                        ?>
                    </div>
                </div>
                <?php
                endforeach;
                ?>
                <div class="col-sm-3">
                    <div class="form-group">
                        <button type="submit" class="btn btn-default float-left"><i class="far fa-filter"></i> Фильтр
                        </button>
                    </div>
                </div>
            </div>
        <?= $this->form()->closeTag() ?>
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->