<?php
$this->breadcrumbs()->setBreadcrumbs([
    [
        'label' => $this->translate('Сотрудники'),
    ],
]);

?>
<!--header title page-->
<div class="row mb-1 mb-lg-3">
    <div class="col-12">
        <div class="header-page">
            <h1><?= $this->translate('Сотрудники'); ?></h1>
        </div>
    </div>
</div>
<!--//header title page-->
<div class="row">
    <div class="col-md-12 col-lg-10 offset-lg-1">
        <form action="<?= $this->url('agent-search') ?>" method="post" name="form-realty-estimate" role="form"
              data-toggle="validator">
            <div class="row form-board">
                <div class="col-md-9">
                    <div class="form-group ">
                        <input type="text" name="code" class="form-control required mb-4" value="<?= $code ?>"
                               placeholder="<?= $this->translate('Код сотрудника') ?>" required="required">
                        <?php
                        if (!empty($error)) { ?>
                            <div class="help"><?= $error ?></div>
                            <?php
                        } ?>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="form-group ">
                        <input type="submit" class="btn btn-default form m-auto"
                               value="<?= $this->translate('Найти') ?>">
                    </div>
                </div>
            </div>
        </form>
        <?= $this->lang()->getDataByLang($page->getContent()); ?>
    </div>
</div>