<?php
$markers = [];
$count = 0;
$lat = 0;
$lng = 0;

if (!empty($realty['lat']) && !empty($realty['lng'])) {

    $markers[] = [
        'lat' => $realty['lat'],
        'lng' => $realty['lng'],
        'label' => $realty['rooms'],
    ];
    $lat = $realty['lat'];
    $lng = $realty['lng'];
}

$markersJson = \Laminas\Json\Encoder::encode($markers);
$script = <<<EOF

    var map;
    
    function initMap() {
        var lat = $lat;
        var lng = $lng;
        var markers = $markersJson;
        var marker = [];
        var infowindow = [];      

        map = new google.maps.Map(document.getElementById('googleMap'), {
            center: {lat: lat, lng: lng},
            zoom: 16,
            zoomControl: true,
            mapTypeControl: true,
            scaleControl: true,
            streetViewControl: true,
            rotateControl: true,
            fullscreenControl: true
        });
        
        // Create markers.
        for (var i = 0; i < markers.length; i++) {
          marker[i] = new google.maps.Marker({
                position: {lat: markers[i]['lat'], lng: markers[i]['lng']},
                label: {color: '#ffffff', text: markers[i]['label'].toString(), fontSize: '16px', fontWeight: '600'},
                index: i,
                map: map
            });
        };
    }
    initMap();
EOF;

if (!empty($lat) && !empty($lng) ) {
    $this->inlineScript()->offsetSetScript(100, $script);
    ?>
    <div class="google-map-ob mb-5">
        <div id="googleMap" tabindex="0" style="display: block; width: 100%; height: 370px"></div>
    </div>
    <?php
}