<?php
$this->breadcrumbs()->setBreadcrumbs([
    [
        'label' => $this->translate('Доска объявлений'),
        'uri' => $this->urlWithLang($this->url('board')),
    ],
    [
        'label' => $this->translate('Объявление отправлено'),
    ],
]);
?>
<div class="row mb-1 mb-lg-3">
    <div class="col-12">
        <div class="header-page">
            <h1><?= $this->translate('Объявление отправлено') ?></h1>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12 col-lg-10 offset-lg-1">
        <div class="row">
            <div class="col-12 coment-board">
                <p class="alert-form">Спасибо, Ваше сообщение успешно отправлено.</p>
            </div>
        </div>
    </div>
</div>
