<?php

namespace Yu\Core\Form\Element;

use Laminas\Filter;
use Laminas\Form\Element\Select as SelectElement;
use Laminas\InputFilter\InputProviderInterface;

class Select extends SelectElement
{

    /**
     * @inheritDoc
     */
    public function setOptions($options)
    {
        $options['value_options'] = [

    ];
        return parent::setOptions($options); // TODO: Change the autogenerated stub
    }


}