<?php
$this->breadcrumbs()->setBreadcrumbs([
    [
        'label' => 'Продажа квартир',
    ],
]);
?>
<div class="row mb-1 mb-lg-3">
    <div class="col-12 col-sm-6 col-md-7 col-lg-8">
        <div class="header-page">
            <h1>Продажа квартир в Мариуполе (р. поиск - Продажа 2-х комнатных квартир в Мариуполе)</h1>
        </div>
    </div>
    <div class="col-12 col-sm-6 col-md-5 col-lg-4 text-center">
        <div class="info-search txt-cond">найдено обектов - <?= count($realtyArray) ?></div>
    </div>
</div>
<!--//header title page-->
<!--link map-->
<?= $this->partial('realty/map/catalog', ['realtyArray' => $realtyArray]); ?>
<!--//link map-->
<!--catalog-->
<div class="row row-cols-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-4 cards-ob">
    <?php
    foreach ($realtyArray as $realty) {
        echo $this->partial('realty/item', ['realty' => $realty]);
    } ?>
</div>
<!--//catalog-->
<div class="container">
    <div class="row">
        <div class="col-md-12 col-lg-10 offset-lg-1">
            <div class="row form-offers-page">
                <div class="col-12 col-lg-4 title">
                    <h5>Не нашли подходящий объект? Оставьте заявку, мы подберем
                        подходящий Вам вариант!</h5>
                    <p class="small mb-1">или позвоните нам по телефону:</p>
                    <span class="txt-cond"><a href="tel:+380629407407">+38 (0629) 407-407</a><br/>
                            <a href="tel:+380687831434">+38 068 783-14-34</a></span></div>
                <div class="col-12 col-lg-8 form-content">
                    <form>
                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Имя">
                                </div>
                                <div class="form-group">
                                    <input type="text" class="form-control" placeholder="Телефон">
                                </div>
                            </div>
                            <div class="col-md-7">
                                <div class="form-group">
                                            <textarea class="form-control" id="text" placeholder="Интересует Продажа 1-комнатная
квартира в Центральном районе
по умолчанию, текст из запроса" style="height:105px;"></textarea>
                                </div>
                                <div class="form-group"><a href="#" class="btn red">Отправить</a></div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>