<?php
/** @var \Yu\Realty\View\Helper\RealtyHelper $realtyHelper */
$realtyHelper = $this->realty();
$type = $this->options['type'];
$this->breadcrumbs()->setBreadcrumbs([
    [
        'label' => $realtyHelper->getLabel($type, 'catalog'),
    ],
]);

?>
    <div class="row mb-1 mb-lg-3">
        <div class="col-12 col-sm-6 col-md-7 col-lg-8">
            <div class="header-page">
                <h1><?= $realtyHelper->getLabel($type, 'catalog') ?> в Мариуполе</h1>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-md-5 col-lg-4 text-center">
            <div class="info-search txt-cond">найдено всего обектов - <?= ($realtyArray->getTotalItemCount()) ?></div>
        </div>
    </div>
    <!--//header title page-->
    <!--link map-->
<?= $this->partial('realty/map/catalog', ['realtyArray' => $realtyArray]); ?>
    <!--//link map-->
    <!--catalog-->
    <div class="row row-cols-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-4 cards-ob">
        <?php
        foreach ($realtyArray as $realty) {
            echo $this->partial('realty/item', ['realty' => $realty]);
        } ?>
    </div>
    <!--//catalog-->
    <!--paginator-->
    <div class="row mt-5">
        <div class="col text-center">
            <?php
            echo $this->paginationControl($realtyArray, 'Elastic', 'layout/paginator', ['route' => $type, 'params' => $this->params]) ?>
        </div>
    </div>
    <!--//paginator-->

<?php
echo $this->partial('layout/not-found-realty');
?>
<?php
$tabId = $realtyHelper->getTabId($type);
$script = <<<EOF
    $(document).ready(function () {
        $('.nav-tabs a[id="$tabId"]').tab('show');
    });
EOF;

$this->inlineScript()->offsetSetScript(90, $script);
?>
