<?php
$markers = [];
$count = 0;
$lat = 0;
$lng = 0;
foreach ($realtyArray as $realty) {
    if (!empty($realty['lat']) && !empty($realty['lng'])) {
        $info = '<div class="img-prev"><img src="' . $this->image()->load('realty', $realty['id'])->resize(480, 347)->get() . '" class="img-fluid" />
                <div class="price-code"><span class="price">' . $this->partial('realty/price', ['realty' => $realty]) . '</span> <span class="cod">код ' . $realty['code'] . '</span>
                </div></div>';
        $markers[] = [
            'lat' => $realty['lat'],
            'lng' => $realty['lng'],
            'label' => $realty['rooms'],
            'info' => $info,
        ];
        $lat = $lat + $realty['lat'];
        $lng = $lng + $realty['lng'];
        $count++;
    }
}
$lat = $lat / $count;
$lng = $lng / $count;
$markersJson = \Laminas\Json\Encoder::encode($markers);
$script = <<<EOF

    var map;
    
    function initMap() {
        var lat = $lat;
        var lng = $lng;
        var markers = $markersJson;
        var marker = [];
        var infowindow = [];      

        map = new google.maps.Map(document.getElementById('googleMap'), {
            center: {lat: lat, lng: lng},
            zoom: 14,
            zoomControl: true,
            mapTypeControl: true,
            scaleControl: true,
            streetViewControl: true,
            rotateControl: true,
            fullscreenControl: true
        });
        
        // Create markers.
        for (var i = 0; i < markers.length; i++) {
          marker[i] = new google.maps.Marker({
                position: {lat: markers[i]['lat'], lng: markers[i]['lng']},
                label: {color: '#ffffff', text: markers[i]['label'].toString(), fontSize: '16px', fontWeight: '600'},
                index: i,
                map: map
            });
            
          infowindow[i] = new google.maps.InfoWindow({
               content: markers[i]['info'],
               maxWidth: 200
            });
            
          marker[i].addListener('click', function() {
                infowindow[this.index].open(map, this);
            });
        };
    }
    initMap();
EOF;

if ($count) {
    $this->inlineScript()->offsetSetScript(100, $script);
    ?>
    <div class="row mb-5">
        <div class="col">
            <div class="d-flex  map-ob"><a class="btn red link-map txt-cond ml-auto" data-toggle="collapse"
                                           href="#map-objects" role="button" aria-expanded="false"
                                           aria-controls="map-objects"><?= $this->translate('Объекты на карте') ?></a>
            </div>
            <div class="collapse fade" id="map-objects">
                <div class="mt-2">
                    <div id="googleMap" tabindex="0" style="display: block; width: 100%; height: 600px"></div>
                </div>
            </div>
        </div>
    </div>
    <?php
}
