<?php
$this->breadcrumbs()->setBreadcrumbs([
    [
        'label' => $this->lang()->getDataByLang($page->getTitle()),
    ],
]);
?>
<!--header title page-->
<div class="row mb-1 mb-lg-3">
    <div class="col-12">
        <div class="header-page">
            <h1><?= $this->lang()->getDataByLang($page->getTitle()); ?></h1>
        </div>
    </div>
</div>
<!--//header title page-->
<div class="row">
    <div class="col-md-4">
        <?= $this->lang()->getDataByLang($page->getContent()); ?>
    </div>
    <div class="col-md-8">
        <div class="map-con">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2714.2257936543137!2d37.56407074854016!3d47.1338422659936!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x40e6e1517d2ca871%3A0xb822ed796d169268!2z0L_RgNC-0YHQvy4g0JzQtdGC0LDQu9C70YPRgNCz0L7QsiwgMTk0LCDQnNCw0YDQuNGD0L_QvtC70YwsINCU0L7QvdC10YbQutCw0Y8g0L7QsdC70LDRgdGC0YwsIDg3NTAw!5e0!3m2!1sru!2sua!4v1585550674603!5m2!1sru!2sua" width="100%" height="500" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>
        </div>
    </div>
</div>