<?php
$this->breadcrumbs()->setBreadcrumbs([
    [
        'label' => $this->lang()->getDataByLang($page->getTitle()),
    ],
]);
?>
<!--header title page-->
<div class="row mb-1 mb-lg-3">
    <div class="col-12">
        <div class="header-page">
            <h1><?= $this->lang()->getDataByLang($page->getTitle()); ?></h1>
        </div>
    </div>
</div>
<!--//header title page-->
<!--body content page-->
<div class="row">
    <div class="col-md-12 col-lg-10 offset-lg-1">
        <?= $this->lang()->getDataByLang($page->getContent()); ?>
    </div>
</div>
<!--//body content page-->
