<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <?php echo $this->headTitle('Панель управления сайтом'); ?>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php
    $this->headLink()
        /** overlayScrollbars */
        ->prependStylesheet($this->basePath('/dist/modules/Yu/Admin/web/plugins/overlayScrollbars/css/OverlayScrollbars.min.css'))
        /** Theme style */
        ->prependStylesheet($this->basePath('/dist/modules/Yu/Admin/web/css/adminlte.css'))
        /** Font Awesome */
        ->prependStylesheet($this->basePath('/dist/modules/Yu/Admin/web/css/fontawesome-free/css/all.css'));

    echo $this->headLink()->toString();
    echo $this->headStyle()->toString();
    ?>
    <!-- Google Font: Source Sans Pro -->
    <?php /*<link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">*/?>
</head>

<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="/admin" class="nav-link">Админ.панель</a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="/" class="nav-link" target="_blank">Перейти на сайт</a>
            </li>
        </ul>

        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
            <!-- Profile -->
            <li class="nav-item dropdown">
                <a class="nav-link" data-toggle="dropdown" href="#">
                    <i class="far fa-user"></i>
                </a>
                <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-item dropdown-header"><i class="fas fa-user"></i> Ваш профиль</span>

                    <div class="dropdown-divider"></div>
                    <span class="dropdown-item dropdown-header">
                        <a href="<?= $this->url('admin/profile') ?>" class="dropdown-item">
                            <i class="fas fa-edit"></i> Редактировать
                        </a>
                    </span>

                    <div class="dropdown-divider"></div>
                    <span class="dropdown-item dropdown-header">
                        <a href="<?= $this->url('admin/login/exit') ?>" class="dropdown-item">
                            <i class="fas fa-power-off"></i> Выход
                        </a>
                    </span>
                </div>
            </li>
        </ul>
    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="/admin" class="brand-link">
            <img src="/dist/modules/Yu/Admin/web/images/AdminLTELogo.png" alt="AdminPANEL"
                 class="brand-image img-circle elevation-3"
                 style="opacity: .8">
            <span class="brand-text font-weight-light">AdminPANEL</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <?= $this->navigation('Laminas\Navigation\Admin')->menu()->setPartial('admin/block/sidebar') ?>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1 class="m-0 text-dark"><?= $this->h1 ?></h1>
                    </div><!-- /.col -->
                    <div class="col-sm-6">
                        <?= $this->navigation('Laminas\Navigation\Admin')->breadcrumbs()->setPartial('admin/block/breadcrumbs') ?>
                    </div><!-- /.col -->
                </div><!-- /.row -->
            </div><!-- /.container-fluid -->
        </div>
        <!-- /.content-header -->
        <div class="col-md-12">
            <?php echo $this->render('admin/block/messenger'); ?>
            <div class="card">
                <?= $this->content ?>
            </div>
        </div>


    </div>
    <!-- /.content-wrapper -->
    <footer class="main-footer">
        <strong>Copyright &copy; <?= date('Y') ?>.</strong>
        All rights reserved.
        <div class="float-right d-none d-sm-inline-block">
            <b>Version</b> 6.0.1
        </div>
    </footer>

</div>
<!-- ./wrapper -->
<?php
$this->inlineScript()
    /** jQuery */
    ->offsetSetFile(10,$this->basePath('/dist/modules/Yu/Admin/web/plugins/jquery/jquery.min.js'))
    /** jQuery UI 1.11.4 */
    ->offsetSetFile(20,$this->basePath('/dist/modules/Yu/Admin/web/plugins/jquery-ui/jquery-ui.min.js'))
    /** Bootstrap 4 */
    ->offsetSetFile(30,$this->basePath('/dist/modules/Yu/Admin/web/plugins/bootstrap/js/bootstrap.bundle.min.js'))
    /** overlayScrollbars */
    ->offsetSetFile(40,$this->basePath('/dist/modules/Yu/Admin/web/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js'))
    /** AdminLTE App */
    ->offsetSetFile(50,$this->basePath('/dist/modules/Yu/Admin/web/js/adminlte.js'));

//echo $this->headScript();
echo $this->inlineScript();
?>
<script>
    $.widget.bridge('uibutton', $.ui.button)
</script>
</body>
</html>
