<!doctype html>
<html lang="ru" class="h-100">
<head>
    <base href="//<?= $_SERVER['HTTP_HOST']; ?>/"/>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Масштаб</title>
    <meta name="description" content="">
    <meta name="keywords" content=" ">
    <link rel="stylesheet" href="/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css">
    <link rel="stylesheet" type="text/css" href="/css/bootstrap-select.min.css">
    <link rel="stylesheet" type="text/css" media="all" href="/css/menutop.css">
    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" type="text/css" href="/css/media.css">
    <link rel="stylesheet" type="text/css" href="/css/media.css">
    <link rel="stylesheet" type="text/css" href="/css/jquery.fancybox.min.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto|Roboto+Condensed:300,400,700&display=swap"
          rel="stylesheet">
    <script src="https://maps.googleapis.com/maps/api/js?key=<?= \Yu\Geo\ValueObject\Map::API_KEY ?>&callback=initMap&language=ua&libraries=visualization"
            async defer></script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
</head>

<body class="d-flex flex-column h-100">
<div id="app">
    <header class="large">
        <div class="container bg-header">
            <div class="wsmenucontainer clearfix">
                <div class="overlapblackbg"></div>
                <div class="wsmobileheader clearfix"><a id="wsnavtoggle" class="animated-arrow"><span></span></a> <a
                            class="smallogo"><img src="/i/logo.png" alt=""/></a>
                    <!--compare-->
                    <div class="callusicon"><a href="<?= $this->urlLang($this->url('compare')) ?>" title="Сравнение" class="compare"><i
                                    class="fas fa-balance-scale"><span class="compare-amount">0</span></i></a></div>
                    <!--//compare-->

                </div>
                <div class="header">

                    <!--Main Menu HTML Code-->
                    <div class="wsmain">
                        <nav class="wsmenu clearfix">
                            <?= $this->navigation('Laminas\Navigation\Top')->menu()->setPartial('layout/menu-top') ?>
                        </nav>
                    </div>
                    <!--Menu HTML Code-->

                </div>
            </div>
            <div class="top-site">
                <div class="row">
                    <div class="col-lg-2 col-xl-3"><a href="/" title="На Главную"><img src="/i/logo.png"
                                                                                       alt="Риэлторская компания Масштаб"/></a>
                    </div>
                    <div class="col-lg-10 col-xl-9">
                        <div class="send-form float-left pt-lg-2 pt-xl-3"><a href="#" class="txt-cond red-top"
                                                                             data-toggle="modal" data-target="#order"><i
                                        class="far fa-check-circle"></i>Подать заявку</a><a href="#"
                                                                                            class="txt-cond red-top"
                                                                                            data-toggle="modal"
                                                                                            data-target="#estimate"><i
                                        class="far fa-check-circle"></i>Оценить недвижимость On-line</a></div>
                        <div class="phon-top pt-lg-2 pt-xl-3"><i class="fas fa-phone"></i><a href="tel:+380629407407"
                                                                                             class="txt-cond mr-4">+38
                                0629
                                407-407</a><a href="tel:+380676259111" class="txt-cond">+38 067 62-59-111</a></div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!--//header-->
    <div class="wraper">
        <!--panel search-->
        <?= $this->partial('layout/search') ?>
        <!--//panel search-->

        <?php
        if (isset($this->isHome) && $this->isHome === true) {
            echo $this->content;
        } else {
            ?>
            <div class="container">
                <div class="row">
                    <div class="col">
                        <?php
                        echo $this->breadcrumbs()->render();
                        ?>
                    </div>
                </div>
                <?= $this->content; ?>
            </div>
            <?php
        }
        ?>

    </div>
</div>
<footer class="mt-auto">
    <div class="container footer">
        <div class="row">
            <div class="col-sm-6 col-lg-3 contact-bt"><img src="i/logo.png" alt="Риэлторская компания Масштаб"/>
                <div class="adres d-sm-inline-flex d-md-flex"><i class="fas fa-map-marker-alt mt-1"></i>
                    <p>Мариуполь,<br/>
                        пр. Металлургов 194
                </div>
                <div class="phone txt-cond d-sm-inline-flex d-md-flex "><i class="fas fa-phone mt-1"></i>
                    <p>+38 (0629) 407-407<br/>
                        +38 068 783-14-34<br/>
                        +38 966 121-34-34</p>
                </div>
            </div>
            <div class="col-sm-6 col-lg-3 d-none d-lg-block pt-2"><strong class="txt-cond">Продаем</strong>
                <ul class="menu-list">
                    <li><a href="#">Квартиры</a></li>
                    <li><a href="#">Дома</a></li>
                    <li><a href="#">Помещение</a></li>
                    <li><a href="#">Земля</a></li>
                    <li><a href="#">Коммерческая недвижимость</a></li>
                </ul>
            </div>
            <div class="col-sm-6 col-lg-3 d-none d-lg-block pt-2"><strong class="txt-cond">Сдаем</strong>
                <ul class="menu-list">
                    <li><a href="#">Квартиры</a></li>
                    <li><a href="#">Дома</a></li>
                    <li><a href="#">Посуточно</a></li>
                    <li><a href="#">Коммерческая недвижимость</a></li>
                </ul>
            </div>
            <div class="col-sm-6 col-lg-3  text-center pt-2">
                <ul class="icon-soc">
                    <li><a href="#" class="text-hide soc vk">ВКонтакте</a></li>
                    <li><a href="#" class="text-hide soc fb">Facebook</a></li>
                    <li><a href="#" class="text-hide soc ins">Instagram</a></li>
                    <li><a href="#" class="text-hide soc ut">YouTube</a></li>
                </ul>
                <img src="i/ulitka.png" alt="" class="ms-ul"/>
                <div class="cop">Риэлторская кампания «МАСШТАБ»<br/>
                    Мариуполь © <?= date('Y') ?>
                </div>
                <div class="rp">Сделано в <a href="https://www.rp-studio.net">RP-Studio</a></div>
            </div>
        </div>
    </div>
</footer>
<a href="#" class="scrollup">Наверх</a>
<?= $this->render('layout/scripts') ?>
<?php
echo $this->inlineScript();
?>
<!--modal compare-yes-->
<div class="modal fade my" id="compare-yes" tabindex="-1" role="dialog" aria-labelledby="compare-yes"
     aria-hidden="true">
    <div class="modal-dialog  modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Закрыть"><span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-1 d-none d-md-block "><i class="fas fa-balance-scale"></i></div>
                    <div class="col-md-7 text-center">
                        <p class="p-0 mt-1">Объект добавлен в "Сравнение"</p>
                    </div>
                    <div class="col-md-4 text-center"><a href="#" class="btn red">Перейти в Сравнение</a></div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--//modal compare-yes-->
<!--modal order-->
<div class="modal fade my" id="order" tabindex="-1" role="dialog" aria-labelledby="order" aria-hidden="true">
    <div class="modal-dialog  modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Закрыть"><span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body pt-4 pb-4">
                <h5>Заявка в кампанию Масштаб</h5>
                <div class="coment"></div>
                <form>
                    <div class="form-group">
                        <input type="text" class="form-control" id="name" placeholder="Ваше имя">
                    </div>
                    <div class="form-group">
                        <input type="text" class="form-control" id="phon" placeholder="Телефон">
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" id="text"
                                  placeholder="Текст заявки если из обявления то - Заголовок Продажа 1-комнатная квартира, Центральный р-н, Мариуполь, ул. 50 лет СССР,  17 ЖМР,  рынок"
                                  style="height:100px;"></textarea>
                    </div>
                    <div class="form-group text-center"><a href="#" type="submit" class="btn form m-auto">Отправить</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<!--//modal order-->
</body>
</html>