<ul class="mobile-sub wsmenu-list">
    <li class="rightmenu">
        <div class="lang">
            <a href="/"<?php if($this->lang()->getCurrentLangCode() == 'ru') echo ' class="active"'?>>RU</a>
            <a href="/ua"<?php if($this->lang()->getCurrentLangCode() == 'ua') echo ' class="active"'?>>UA</a>
            <a href="/en"<?php if($this->lang()->getCurrentLangCode() == 'en') echo ' class="active"'?>>EN</a>
        </div>
    </li>
    <?php
    foreach ($this->container as $menu1) {
        /** @var \Laminas\Navigation\Page\Uri $menu1 */
        ?>
        <li><a href="<?= $this->urlWithLang($menu1->getHref()); ?>"<?php if($menu1->isActive()) { echo ' class="active"'; }; ?>><?= $this->translate($menu1->getLabel()) ?><?php
                if ($menu1->hasPages()) {
                    echo '<span class="arrow fas fa-angle-down"></span>';
                }
                ?></a><?php
            if ($menu1->hasPages()) { ?>
                <ul class="wsmenu-submenu"><?php
                foreach ($menu1 as $menu2) {
                    /** @var \Laminas\Navigation\Page\Uri $menu2 */
                    ?>
                    <li><a href="<?= $this->urlWithLang($menu2->getHref()); ?>"<?php if($menu2->isActive()) { echo ' class="active"'; }; ?>><?= $this->translate($menu2->getLabel()) ?></a></li>
                    <?php
                }
                ?>
                </ul><?php
            }
            ?>
        </li>
        <?php
    }
    ?>
    <li class="menu-hide"><a href="#" data-toggle="modal" data-target="#order" class="txt-cond"><i
                    class="far fa-check-circle"></i>Подать заявку</a></li>
    <li class="menu-hide"><a href="#" data-toggle="modal" data-target="#estimate"
                             class="txt-cond"><i class="far fa-check-circle"></i>Оценить
            недвижимость On-line</a></li>
</ul>