<div class="container">
    <div class="row">
        <div class="col-md-12 col-lg-10 offset-lg-1">
            <div class="row form-offers-page">
                <div class="col-12 col-lg-4 title">
                    <h5><?= $this->translate('Не нашли подходящий объект? Оставьте заявку, мы подберем подходящий Вам вариант!') ?></h5>
                    <p class="small mb-1"><?= $this->translate('или позвоните нам по телефону')?>:</p>
                    <span class="txt-cond"><?= $this->lang($this->content()->getBlock('bottom_phones')) ?></div>
                <div class="col-12 col-lg-8 form-content">
                    <form name="form-realty-find" action="">
                        <input type="hidden" name="type" value="realty-find">
                        <div class="row">
                            <div class="col-md-5">
                                <div class="form-group">
                                    <input type="text" name="name" class="form-control" placeholder="<?= $this->translate('Ваше имя')?>" required>
                                </div>
                                <div class="form-group">
                                    <input type="text" name="phone" class="form-control" placeholder="<?= $this->translate('Телефон')?>" required>
                                </div>
                            </div>
                            <div class="col-md-7">
                                <div class="form-group">
                                            <textarea class="form-control" id="message" name="message" placeholder="<?= $this->translate('Сообщение')?>" style="height:105px;"></textarea>
                                </div>
                                <div class="form-group"><a type="submit" class="btn red feedback-send"><?= $this->translate('Отправить')?></a></div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>