<?php
if ($this->pageCount):
    $path = '';
    if (isset($this->path)) {
        $path = $this->path;
    }
    $_params = [];
    foreach ($this->params as $key => $value) {
        if ($key != 'page') {
            $_params[$key] = $value;
        }
    }
    ?>

    <div class="paginator">
        <strong>Страницы</strong>
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <a href="<?= $this->url($this->route, array_merge(['page' => $this->previous], $_params), ['query' => array_merge(['page' => $this->previous], $_params)]); ?>">
                ← предыдущая
            </a>
        <?php else: ?>
            ← предыдущая
        <?php endif; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <a href="<?= $this->url($this->route, array_merge(['page' => $this->next], $_params), ['query' => array_merge(['page' => $this->next], $_params)]); ?>">
                следующая →
            </a>
        <?php else: ?>
            следующая →
        <?php endif; ?>
    </div>

    <div class="paginator mt-3">
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <a href="<?= $this->url($this->route, array_merge(['page' => $page], $_params), ['query' => array_merge(['page' => $page], $_params)]); ?>">
                    <?= $page; ?>
                </a>
            <?php else: ?>
                <span class="ak"><?= $page; ?></span>
            <?php endif; ?>
        <?php endforeach; ?>
    </div>

<?php endif; ?>
