<?php
/*
$this->headTitle($this->lang($this->seo()->getTitle($metaKeys)));
$this->headMeta($this->lang($this->seo()->getDescription($metaKeys)),'description');
$this->headMeta($this->lang($this->seo()->getKeywords($metaKeys)),'keywords');
*/
?>
<div class="container">
    <h1 class="index"><span><?= $this->translate('Недвижимость Мариуполя') ?></span> &mdash;
<?= $this->translate('продажа') ?>, <?= $this->translate('аренда') ?>, <?= $this->translate('посуточно') ?></h1>
</div>
<!--vitrina-->
<div class="container-fluid vitrina">
    <div class="row">
        <div class="item col-sm-12 col-lg-8  wow fadeInLeft" data-wow-delay="0.1s"><a href="<?= $this->urlWithLang($this->url('sale-flat')) ?>">
                <div class="header txt-cond">
                    <h4><?= $this->translate('Купить квартиру в Мариуполе') ?></h4>
                    <span><?= $this->realty()->getCount('sale-flat'); ?></span> <?= $this->translate('предложений') ?>
                </div>
                <div class="img-hover-zoom"><img src="i/in_kvartira_arend.jpg" class="img-fluid pik"
                                                 alt="<?= $this->translate('Снять квартиру в Мариуполе') ?>"/></div>
            </a></div>
        <div class="item col-sm-6 col-lg-4  wow fadeInRight" data-wow-delay="0.1s"><a href="<?= $this->urlWithLang($this->url('rent-flat')) ?>">
                <div class="header txt-cond">
                    <h4><?= $this->translate('Снять квартиру в Мариуполе') ?></h4>
                    <span><?= $this->realty()->getCount('rent-flat'); ?></span> <?= $this->translate('предложений') ?>
                </div>
                <div class="img-hover-zoom"><img src="i/in_kvartira.jpg" class="img-fluid"
                                                 alt="<?= $this->translate('Купить квартиру в Мариуполе') ?>"/></div>
            </a></div>
        <div class="item col-sm-6 col-lg-4  wow fadeInLeft" data-wow-delay="0.2s"><a href="<?= $this->urlWithLang($this->url('sale-house')) ?>">
                <div class="header txt-cond">
                    <h4><?= $this->translate('Купить дом в Мариуполе') ?></h4>
                    <span><?= $this->realty()->getCount('sale-house'); ?></span> <?= $this->translate('предложений') ?>
                </div>
                <div class="img-hover-zoom"><img src="i/in_dom.jpg" class="img-fluid" alt="<?= $this->translate('Купить дом в Мариуполе') ?>"/>
                </div>
            </a></div>
        <div class="item col-sm-6 col-lg-4  wow fadeIn" data-wow-delay="0.3s"><a href="<?= $this->urlWithLang($this->url('rent-house')) ?>">
                <div class="header txt-cond">
                    <h4><?= $this->translate('Снять дом в Мариуполе')?></h4>
                    <span><?= $this->realty()->getCount('rent-house'); ?></span> <?= $this->translate('предложений') ?>
                </div>
                <div class="img-hover-zoom"><img src="i/in_dom_arend.jpg" class="img-fluid"
                                                 alt="<?= $this->translate('Снять дом в Мариуполе')?>"/></div>
            </a></div>
        <div class="item col-sm-6 col-lg-4 wow fadeInRight" data-wow-delay="0.2s"><a href="<?= $this->urlWithLang($this->url('rent-apartment')) ?>">
                <div class="header txt-cond">
                    <h4><?= $this->translate('Снять квартиру посуточно в Мариуполе')?></h4>
                    <span><?= $this->realty()->getCount('rent-apartment'); ?></span> <?= $this->translate('предложений') ?>
                </div>
                <div class="img-hover-zoom"><img src="i/in_kvartira_day.jpg" class="img-fluid"
                                                 alt="<?= $this->translate('Снять квартиру посуточно в Мариуполе')?>"/></div>
            </a></div>
    </div>
</div>
<!--//vitrina-->
<!--block hot-->
<?php
$realtyHot = $this->realty()->getRealtyHot(null,['id' => 'DESC'],8);
if(count($realtyHot)) {
    ?>
    <div class="container hot-index">
        <div class="d-flex header-hot align-items-center"><span class="txt-cond"><?= $this->translate('Горячие предложения')?></span><span
                    class="dec w-100"></span></div>
        <div class="row row-cols-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-4 cards-ob">
            <?php
            foreach ($realtyHot as $itemHot) {
                $item = $this->realty()->getRealtyItem($itemHot->getId(), $itemHot->getType());
                if($item !== null) {
                    echo $this->partial('realty/item', ['realty' => $item]);
                }
            }
            ?>
        </div>
        <div class="text-center"><a href="<?= $this->urlWithLang($this->url('hot')) ?>" class="btn red"><?= $this->translate('Показать все предложения')?></a></div>
    </div>
    <?php
}
?>
<!--//block hot-->
<!--mashtab buy-->
<div class="company-buy">
    <div class="header">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h3><?= $this->translate('РК Масштаб - купит - снимет - обменяет')?></h3>
                    <a href="<?= $this->urlWithLang($this->url('buy')) ?>"><?= $this->translate('Все объявления')?></a></div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
            <?php
            $i = 1;
            $buy = $this->catalogHelper()->getCatalog(['catalog.active' => 1],['catalog.sort' => 'DESC'], 4);
            foreach($buy as $b) {
                ?>
                <div class="col item wow <?php if(in_array($i,[1,2])) { echo 'fadeInLeft'; } else { echo 'fadeInRight'; } ?>" data-wow-delay="<?php if(in_array($i,[2,3])) { echo '0.1s'; } else { echo '0.2s'; } ?>">
                    <div class="card ">
                        <h6><?= $this->lang()->getDataByLang($b['name']) ?></h6>
                        <?= $this->lang()->getDataByLang($b['content']) ?>
                        <p class="contact"><strong>т. <?= $b['phone']?></strong><br/>
                            <a href="mailto:<?= $b['email'] ?>"><?= $b['email'] ?></a></p>
                    </div>
                </div>
                <?php
                $i++;
            }
            ?>
        </div>
    </div>
</div>
<!--//mashtab buy-->
<!--info company-->
<div class="container info-index">
    <div class="row">
        <div class="col-md-5 col-lg-4 poll-block-main">
            <?= $this->partial('yu/poll/block/block'); ?>
        </div>
        <div class="col-md-7 col-lg-8 pl-lg-5 pl-sm-4">
            <?= $this->lang($this->page->getContent()) ?>
        </div>
    </div>
</div>
<!--//info company-->
<!--section work-->
<div class="container work">
    <h4><?= $this->translate('Как мы работаем')?></h4>
    <div class="row d-flex justify-content-center">
        <div class="line d-none d-md-block"></div>
        <div class="col"><i class="far fa-edit pl-2"></i> <span class="txt-cond"><?= $this->translate('Заказ')?></span>
            <p><?= $this->translate('Закажите звонок или оставьте заявку')?></p>
        </div>
        <div class="col"><i class="fas fa-user-tie"></i> <span class="txt-cond"><?= $this->translate('Консультация')?></span>
            <p><?= $this->translate('Наш специалист свяжется с Вами')?></p>
        </div>
        <div class="col"><i class="far fa-eye"></i> <span class="txt-cond"><?= $this->translate('Осмотр')?></span>
            <p><?= $this->translate('Осмотр подходящей недвижимости')?></p>
        </div>
        <div class="col"><i class="far fa-file-alt"></i> <span class="txt-cond"><?= $this->translate('Договор')?></span>
            <p><?= $this->translate('Подготовка документации')?></p>
        </div>
        <div class="col"><i class="fas fa-key"></i> <span class="txt-cond"><?= $this->translate('Результат')?></span>
            <p><?= $this->translate('Получение ожидаемого результата')?></p>
        </div>
    </div>
</div>
<!--//section work-->