<div class="container">
    <h1 class="index"><span><?= $this->translate('Недвижимость Мариуполя') ?></span> &mdash;
<?= $this->translate('продажа') ?>, <?= $this->translate('аренда') ?>, <?= $this->translate('посуточно') ?></h1>
</div>
<!--vitrina-->
<div class="container-fluid vitrina">
    <div class="row">
        <div class="item col-sm-12 col-lg-8  wow fadeInLeft" data-wow-delay="0.1s"><a href="#">
                <div class="header txt-cond">
                    <h4><?= $this->translate('Снять квартиру в Мариуполе') ?></h4>
                    <span><?= $this->realty()->getCount('rent-flat'); ?></span> <?= $this->translate('предложений') ?>
                </div>
                <div class="img-hover-zoom"><img src="i/in_kvartira_arend.jpg" class="img-fluid pik"
                                                 alt="<?= $this->translate('Снять квартиру в Мариуполе') ?>"/></div>
            </a></div>
        <div class="item col-sm-6 col-lg-4  wow fadeInRight" data-wow-delay="0.1s"><a href="#">
                <div class="header txt-cond">
                    <h4><?= $this->translate('Купить квартиру в Мариуполе') ?></h4>
                    <span><?= $this->realty()->getCount('sale-flat'); ?></span> <?= $this->translate('предложений') ?>
                </div>
                <div class="img-hover-zoom"><img src="i/in_kvartira.jpg" class="img-fluid"
                                                 alt="<?= $this->translate('Купить квартиру в Мариуполе') ?>"/></div>
            </a></div>
        <div class="item col-sm-6 col-lg-4  wow fadeInLeft" data-wow-delay="0.2s"><a href="#">
                <div class="header txt-cond">
                    <h4><?= $this->translate('Купить дом в Мариуполе') ?></h4>
                    <span><?= $this->realty()->getCount('sale-house'); ?></span> <?= $this->translate('предложений') ?>
                </div>
                <div class="img-hover-zoom"><img src="i/in_dom.jpg" class="img-fluid" alt="<?= $this->translate('Купить дом в Мариуполе') ?>"/>
                </div>
            </a></div>
        <div class="item col-sm-6 col-lg-4  wow fadeIn" data-wow-delay="0.3s"><a href="#">
                <div class="header txt-cond">
                    <h4><?= $this->translate('Снять дом в Мариуполе')?></h4>
                    <span><?= $this->realty()->getCount('rent-house'); ?></span> <?= $this->translate('предложений') ?>
                </div>
                <div class="img-hover-zoom"><img src="i/in_dom_arend.jpg" class="img-fluid"
                                                 alt="<?= $this->translate('Снять дом в Мариуполе')?>"/></div>
            </a></div>
        <div class="item col-sm-6 col-lg-4 wow fadeInRight" data-wow-delay="0.2s"><a href="#">
                <div class="header txt-cond">
                    <h4><?= $this->translate('Снять квартиру посуточно в Мариуполе')?></h4>
                    <span><?= $this->realty()->getCount('rent-apartment'); ?></span> <?= $this->translate('предложений') ?>
                </div>
                <div class="img-hover-zoom"><img src="i/in_kvartira_day.jpg" class="img-fluid"
                                                 alt="<?= $this->translate('Снять квартиру посуточно в Мариуполе')?>"/></div>
            </a></div>
    </div>
</div>
<!--//vitrina-->
<!--block hot-->
<div class="container hot-index">
    <div class="d-flex header-hot align-items-center"><span class="txt-cond">Горячие предложения</span><span
                class="dec w-100"></span></div>
    <div class="row row-cols-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-4 cards-ob">
        <div class="col item wow fadeIn">
            <div class="card"><a href="#">
                    <div class="card-header">
                        <h5>Продается квартира</h5>
                    </div>
                    <div class="img-prev"><img src="i/prev_ob_kv1.jpg" class="img-fluid" alt=""/>
                        <div class="price-code"><span class="price">22000 у.е</span> <span
                                    class="cod">код 16893</span></div>
                        <i class="add-compare fas fa-balance-scale" title="Добавить в сравнение" role="button"
                           data-toggle="modal" data-target="#compare-yes"></i></div>
                    <div class="card-body">
                        <div class="d-flex chart-ob ">
                            <div class="mkv">220 м.кв.</div>
                            <div class="room ml-auto">2 комнаты</div>
                        </div>
                        <p class="adres">Кальмиусский, Мариуполь</p>
                    </div>
                </a></div>
        </div>
        <div class="col item wow fadeIn">
            <div class="card"><a href="#">
                    <div class="card-header">
                        <h5>Сдается квартира посуточно</h5>
                    </div>
                    <div class="img-prev"><img src="i/prev_ob_kv2.jpg" class="img-fluid" alt=""/>
                        <div class="price-code"><span class="price">22000 у.е</span> <span
                                    class="cod">код 16893</span></div>
                        <i class="add-compare fas fa-balance-scale" title="Добавить в сравнение" role="button"
                           data-toggle="modal" data-target="#compare-yes"></i></div>
                    <div class="card-body">
                        <div class="d-flex chart-ob ">
                            <div class="mkv">220 м.кв.</div>
                            <div class="room ml-auto">2 комнаты</div>
                        </div>
                        <p class="adres">Центральный, Мариуполь</p>
                    </div>
                </a></div>
        </div>
        <div class="col item wow fadeIn">
            <div class="card"><a href="#">
                    <div class="card-header">
                        <h5>Продается дом</h5>
                    </div>
                    <div class="img-prev"><img src="i/prev_ob_dom1.jpg" class="img-fluid" alt=""/>
                        <div class="price-code"><span class="price">22000 у.е</span> <span
                                    class="cod">код 16893</span></div>
                        <i class="add-compare fas fa-balance-scale" title="Добавить в сравнение" role="button"
                           data-toggle="modal" data-target="#compare-yes"></i></div>
                    <div class="card-body">
                        <div class="d-flex chart-ob ">
                            <div class="mkv">220 м.кв.</div>
                            <div class="room ml-auto">2 комнаты</div>
                        </div>
                        <p class="adres">Кальмиусский, Мариуполь, ПГТ Талаковка</p>
                    </div>
                </a></div>
        </div>
        <div class="col item wow fadeIn">
            <div class="card"><a href="#">
                    <div class="card-header">
                        <h5>Сдается квартира</h5>
                    </div>
                    <div class="img-prev"><img src="i/prev_ob_kv2.jpg" class="img-fluid" alt=""/>
                        <div class="price-code"><span class="price">22000 у.е</span> <span
                                    class="cod">код 1689356</span></div>
                        <i class="add-compare fas fa-balance-scale" title="Добавить в сравнение" role="button"
                           data-toggle="modal" data-target="#compare-yes"></i></div>
                    <div class="card-body">
                        <div class="d-flex chart-ob ">
                            <div class="mkv">220 м.кв.</div>
                            <div class="room ml-auto">2 комнаты</div>
                        </div>
                        <p class="adres">Примоский, Мариуполь</p>
                    </div>
                </a></div>
        </div>
        <div class="col item wow fadeIn">
            <div class="card"><a href="#">
                    <div class="card-header">
                        <h5>Продается квартира</h5>
                    </div>
                    <div class="img-prev"><img src="i/prev_ob_kv1.jpg" class="img-fluid" alt=""/>
                        <div class="price-code"><span class="price">22000 у.е</span> <span
                                    class="cod">код 16893</span></div>
                        <i class="add-compare fas fa-balance-scale" title="Добавить в сравнение" role="button"
                           data-toggle="modal" data-target="#compare-yes"></i></div>
                    <div class="card-body">
                        <div class="d-flex chart-ob ">
                            <div class="mkv">220 м.кв.</div>
                            <div class="room ml-auto">2 комнаты</div>
                        </div>
                        <p class="adres">Кальмиусский, Мариуполь</p>
                    </div>
                </a></div>
        </div>
        <div class="col item wow fadeIn">
            <div class="card"><a href="#">
                    <div class="card-header">
                        <h5>Сдается квартира посуточно</h5>
                    </div>
                    <div class="img-prev"><img src="i/prev_ob_kv2.jpg" class="img-fluid" alt=""/>
                        <div class="price-code"><span class="price">22000 у.е</span> <span
                                    class="cod">код 16893</span></div>
                        <i class="add-compare fas fa-balance-scale" title="Добавить в сравнение" role="button"
                           data-toggle="modal" data-target="#compare-yes"></i></div>
                    <div class="card-body">
                        <div class="d-flex chart-ob ">
                            <div class="mkv">220 м.кв.</div>
                            <div class="room ml-auto">2 комнаты</div>
                        </div>
                        <p class="adres">Центральный, Мариуполь</p>
                    </div>
                </a></div>
        </div>
        <div class="col item wow fadeIn">
            <div class="card"><a href="#">
                    <div class="card-header">
                        <h5>Продается дом</h5>
                    </div>
                    <div class="img-prev"><img src="i/prev_ob_dom1.jpg" class="img-fluid" alt=""/>
                        <div class="price-code"><span class="price">22000 у.е</span> <span
                                    class="cod">код 16893</span></div>
                        <i class="add-compare fas fa-balance-scale" title="Добавить в сравнение" role="button"
                           data-toggle="modal" data-target="#compare-yes"></i></div>
                    <div class="card-body">
                        <div class="d-flex chart-ob ">
                            <div class="mkv">220 м.кв.</div>
                            <div class="room ml-auto">2 комнаты</div>
                        </div>
                        <p class="adres">Кальмиусский, Мариуполь, ПГТ Талаковка</p>
                    </div>
                </a></div>
        </div>
        <div class="col item wow fadeIn">
            <div class="card"><a href="#">
                    <div class="card-header">
                        <h5>Сдается квартира</h5>
                    </div>
                    <div class="img-prev"><img src="i/prev_ob_kv2.jpg" class="img-fluid" alt=""/>
                        <div class="price-code"><span class="price">22000 у.е</span> <span
                                    class="cod">код 1689356</span></div>
                        <i class="add-compare fas fa-balance-scale" title="Добавить в сравнение" role="button"
                           data-toggle="modal" data-target="#compare-yes"></i></div>
                    <div class="card-body">
                        <div class="d-flex chart-ob ">
                            <div class="mkv">220 м.кв.</div>
                            <div class="room ml-auto">2 комнаты</div>
                        </div>
                        <p class="adres">Примоский, Мариуполь</p>
                    </div>
                </a></div>
        </div>
    </div>
    <div class="text-center"><a href="#" class="btn red">Показать все предложения</a></div>
</div>
<!--//block hot-->
<!--mashtab buy-->
<div class="company-buy">
    <div class="header">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h3>РК Масштаб - купит - снимет - обменяет</h3>
                    <a href="#">Все объявления</a></div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
            <div class="col item wow fadeInLeft" data-wow-delay="0.2s">
                <div class="card ">
                    <h6>Куплю 1 к.кв.</h6>
                    <p>Cрочно! Купим 1 к.кв. в Жовтневом районе. Рассматриваем район от 17 до 23 ЖМР. Обязательное
                        требование: хорошее состояние, ремонт сан/узла. </p>
                    <p class="contact"><strong>т. 097-165-87-18</strong><br/>
                        <a href="#" mailto:"inna-april@bk.ru">inna-april@bk.ru</a></p>
                </div>
            </div>
            <div class="col item wow fadeInLeft" data-wow-delay="0.1s">
                <div class="card ">
                    <h6>Куплю 1 к.кв.</h6>
                    <p>Cрочно! Купим 1 к.кв. в Жовтневом районе. Рассматриваем район от 17 до 23 ЖМР. Cрочно! Купим
                        1 к.кв. в Жовтневом районе. Рассматриваем район от 17 до 23 ЖМР. Обязательное требование:
                        хорошее состояние, ремонт сан/узла. </p>
                    <p class="contact"><strong>т. 097-165-87-18</strong><br/>
                        <a href="#" mailto:"inna-april@bk.ru">inna-april@bk.ru</a></p>
                </div>
            </div>
            <div class="col item d-none d-md-block wow fadeInRight" data-wow-delay="0.1s">
                <div class="card ">
                    <h6>Куплю 1 к.кв.</h6>
                    <p>Cрочно! Купим 1 к.кв. в Жовтневом районе. Рассматриваем район от 17 до 23 ЖМР. Обязательное
                        требование: хорошее состояние, ремонт сан/узла. </p>
                    <p class="contact"><strong>т. 097-165-87-18</strong><br/>
                        <a href="#" mailto:"inna-april@bk.ru">inna-april@bk.ru</a></p>
                </div>
            </div>
            <div class="col item d-none d-lg-block wow fadeInRight" ata-wow-delay="0.2s">
                <div class="card">
                    <h6>Куплю 1 к.кв.</h6>
                    <p>Cрочно! Купим 1 к.кв. в Жовтневом районе. Рассматриваем район от 17 до 23 ЖМР. Обязательное
                        требование: хорошее состояние, ремонт сан/узла. </p>
                    <p class="contact"><strong>т. 097-165-87-18</strong><br/>
                        <a href="#" mailto:"inna-april@bk.ru">inna-april@bk.ru</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
<!--//mashtab buy-->
<!--info company-->
<div class="container info-index">
    <div class="row">
        <div class="col-md-5 col-lg-4">
            <!--//poll vopros-->
            <div class="poll-block">
                <div class="poll-top">
                    <h5>Опрос</h5>
                    <a href="arhiv-poll.html">Проведенные опросы</a></div>
                <div class="poll-container">
                    <form action="">
                        <div class="question">Какой комнаты не хватает в вашей квартире?</div>
                        <div class="poll-body">
                            <div class="form-check">
                                <label class="form-check-label radio" for="q1">
                                    <input class="form-check-input radio" type="radio" name="poll" id="q1"
                                           value="q1" checked>
                                    <div class="radio__text">Вариант ответа не длинный</div>
                                </label>
                            </div>
                            <div class="form-check">
                                <label class="form-check-label radio" for="q2">
                                    <input class="form-check-input radio" type="radio" name="poll" id="q2"
                                           value="q2" checked>
                                    <div class="radio__text">Вариант ответа довольно длинный на две-три строки или
                                        даже больше при необходимости
                                    </div>
                                </label>
                            </div>
                            <div class="form-check">
                                <label class="form-check-label radio" for="q3">
                                    <input class="form-check-input radio" type="radio" name="poll" id="q3"
                                           value="q3" checked>
                                    <div class="radio__text">Коротко</div>
                                </label>
                            </div>
                        </div>
                        <div class="poll-footer"><a href="#" class="btn form">Отправить</a></div>
                    </form>
                </div>
            </div>
            <!--//poll vopros-->
            <!--poll rezultat
            <br/>
            <div class="poll-block">
                <div class="poll-container">
                    <div class="question">Какой комнаты не хватает в вашей квартире?</div>
                    <div class="poll-body">
                        <div class="poll-progress">
                            <div class="poll-procent">0%</div>
                            <div>Вариант ответа не длинный
                                <div class="progress">
                                    <div class="progress-bar" role="progressbar" style="width: 0%" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                        <div class="poll-progress">
                            <div class="poll-procent">100%</div>
                            <div>Вариант ответа довольно длинный на две-три строки или даже больше при необходимости
                                <div class="progress">
                                    <div class="progress-bar" role="progressbar" style="width: 100%" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                        <div class="poll-progress">
                            <div class="poll-procent">10%</div>
                            <div>Вариант ответа довольно длинный на две-три строки или даже больше при необходимости
                                <div class="progress">
                                    <div class="progress-bar" role="progressbar" style="width: 10%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="poll-footer">Голосов 234</div>
                </div>
            </div>
            //poll rezultat-->
        </div>
        <div class="col-md-7 col-lg-8 pl-lg-5 pl-sm-4">
            <h2>Риэлторская компания Масштаб &mdash; вся недвижимость Мариуполя</h2>
            <p>- 21 августа 2017 г. предприятию исполнится 17 лет. За этот сравнительно небольшой период времени мы
                зарекомендовали себя как успешное агентство недвижимости.</p>
            <p>- Удобное расположение, нашего собственного, офиса дает возможность быть ближе к нашим клиентам. </p>
            <p>- Наша собственная уникальная база данных содержит информацию об объектах недвижимости, собранную за
                значительный отрезок времени.</p>
            <p>- У нас больший кредит доверия среди населения города, 98% мариупольцев знают РК "Масштаб".</p>
            <p>- Непосредственный руководитель вышел из среды риэлторов и является собственником компании, что
                способствует увеличению ее рабочего потенциала и боеготовности.</p>
            <p>- В 2006 году РК «Масштаб» была признана лауреатом национального рейтинга Союза специалистов
                недвижимого имущества и вошла в двадцатку лучших в стране риэлторских компаний, а в 2007 году
                получила награду «Лучшая риэлторская кампания».</p>
        </div>
    </div>
</div>
<!--//info company-->
<!--section work-->
<div class="container work">
    <h4>Как мы работаем</h4>
    <div class="row d-flex justify-content-center">
        <div class="line d-none d-md-block"></div>
        <div class="col"><i class="far fa-edit pl-2"></i> <span class="txt-cond">Заказ</span>
            <p>Закажите звонок или оставьте заявку</p>
        </div>
        <div class="col"><i class="fas fa-user-tie"></i> <span class="txt-cond">Консультация</span>
            <p>Наш специалист свяжется с Вами</p>
        </div>
        <div class="col"><i class="far fa-eye"></i> <span class="txt-cond">Осмотр</span>
            <p>Осмотр подходящей недвижимости</p>
        </div>
        <div class="col"><i class="far fa-file-alt"></i> <span class="txt-cond">Договор</span>
            <p>Подготовка документации</p>
        </div>
        <div class="col"><i class="fas fa-key"></i> <span class="txt-cond">Результат</span>
            <p>Получение ожидаемого результата</p>
        </div>
    </div>
</div>
<!--//section work-->