<!-- /.card-header -->
<?php
echo $this->flashMessenger()
    ->setMessageOpenFormat('
                <div class="alert alert-success alert-dismissible">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <i class="icon fas fa-check"></i>Ok! ')
    ->setMessageSeparatorString('')
    ->setMessageCloseString('</div>')
    ->render('success');
?>
<?php
echo $this->flashMessenger()
    ->setMessageOpenFormat('
                <div class="alert alert-danger alert-dismissible">
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                  <h5><i class="icon fas fa-ban"></i>Error!</h5>')
    ->setMessageSeparatorString('')
    ->setMessageCloseString('</div>')
    ->render('error');
?>
<!-- /.card-body -->